### ISSUE TITLE
Use deprecated class cause the snackbar not clickable

### ISSUE THREAD

**Issue by Jack-Works** [iamhosseindhv/notistack#394]
In code https://github.com/iamhosseindhv/notistack/blob/1806f3080cc16ae7cd469db7c99164ea331f2f16/src/SnackbarContainer.tsx#L8
it uses the deprecated class name https://github.com/mui-org/material-ui/pull/24084

And cause the `pointer-events: all` not set. The whole snack bar becomes unclickable.

**Comment by Jack-Works** [comment]
Change it to ` container: '& > .MuiCollapse-root', ` fixes our bug.

**Comment by liuyisnake** [comment]
have the same issue
and i found dom tree container has the class MuiCollapse-container**-364**
which has a random number append the class name

**Comment by manuelcanepa** [comment]
There is a workaround for this?

**Comment by XmelesX** [comment]
🔥 Fast fix:
added `style={{pointerEvents: 'all'}}` to your `SnackbarProvider`

**Comment by simplecommerce** [comment]
I don't use the clickable so I don't get the same issue but I do see these errors everywhere in my console

> Material-UI: The key `container` provided to the classes prop is not implemented in ForwardRef(Collapse). You can only override one of the following: root,entered,hidden,wrapper,wrapperInner.

**Comment by iamhosseindhv** [comment]
Apologies for responding late. Please follow the issue template. `Collapse` component accepts `container` key if you're using MUI < `v4.12.0` and `root` key if you're using MUI >= `v4.12.0`.

If you're using MUI v5, use`npm i notistack@next`
If you're using MUI  >= `v4.12.0`, I'd suggest going with the [above](https://github.com/iamhosseindhv/notistack/issues/394#issuecomment-877688487) approach.

Please let me know if you're having issues with the solutions above.

**Comment by Methuselah96** [comment]
@iamhosseindhv Upgrading to `v4.12.0` also seems to make it so there's no space between multiple notifications.

Before:
![image](https://user-images.githubusercontent.com/693755/125809245-1eae2282-40db-45d4-8bf9-d6f1ab24fc76.png)

After:
![image](https://user-images.githubusercontent.com/693755/125809126-4dcab351-c903-4f52-acb3-ae9a0e8e11d6.png)

**Comment by XmelesX** [comment]
You can make something like this.
Make control of styles to jss.

style.ts:
```tsx
import {makeStyles, Theme} from '@material-ui/core/styles';

export default makeStyles((theme: Theme) => ({
  root: {
    margin: theme.spacing(.75, 0),
    pointerEvents: 'all',
  }
}));
```

index.tsx:
```tsx
import React from 'react';
import {SnackbarProvider, SnackbarProviderProps} from 'notistack';
import useStyles from './style';

export default function Provider(props: SnackbarProviderProps): JSX.Element {
  const classes = useStyles();
  return <SnackbarProvider className={classes.root} {...props}/>;
}
```

**Comment by iamhosseindhv** [comment]
This issue has been fixed in notistack `v1.0.10`

**Comment by bartvde** [comment]
The fix doesn't work for people using createGenerateClassName with disableGlobal true in material-ui

https://material-ui.com/styles/api/

**Comment by MatiasCiccone** [comment]
as @bartvde mentioned this is still an issue for those who use `createGenerateClassName` with `disableGlobal: true`

**Comment by BrentFarese** [comment]
> as @bartvde mentioned this is still an issue for those who use `createGenerateClassName` with `disableGlobal: true`

We have this issue and need to use `disableGlobal: true` to [use DataGridPro V5 w/ MUI V4](https://mui.com/x/react-data-grid/migration-v4/#using-mui-core-v4-with-v5).  @bartvde or @MatiasCiccone did either of you come up with a fix that works while still using `disableGlobal: true`?
